services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ssch\LegacyExtension\:
    resource: '../Classes/*'

  Ssch\LegacyExtension\Controller\:
    resource: '../Classes/Controller/*'
    public: true

  Ssch\LegacyExtension\EventListener\ExampleListener:
    public: true
    tags:
      - name: event.listener
        identifier: 'dev/days/example'